delay: 1000
targets:
  - action:
      actionType: NOTHING
      targetText: text
      locationX: 560
      locationY: 550
    areaX: 500
    areaY: 500
    areaWidth: 100
    areaHeight: 120
  - action:
      actionType: NOTHING
      targetText: text
      locationX: 670
      locationY: 550
    areaX: 610
    areaY: 500
    areaWidth: 100
    areaHeight: 120
  - action:
      actionType: NOTHING
      targetText: text
      locationX: 760
      locationY: 550
    areaX: 710
    areaY: 500
    areaWidth: 100
    areaHeight: 120

beforeActionsList:
  delayBetweenActions: 500
  listActions:
      - actionType: NOTHING
        targetText: t
        locationX: 345
        locationY: 567

afterActionsList:
  delayBetweenActions: 500
  listActions:
      - actionType: NOTHING
        targetText: t
        locationX: 345
        locationY: 787
